// This file is automatically generated. Do not edit it directly.
// Supabase is no longer used. This file remains to avoid breaking imports.
// If imported, it will throw to indicate migration to REST API is required.

export const supabase = new Proxy({}, {
  get() {
    throw new Error('Supabase client is deprecated. Use REST API via src/integrations/api/client.ts');
  }
}) as any;
// Import replacement:
// import { api } from '@/integrations/api/client';